language: packer
sudo: required
dist: trusty
before_install:
  - sudo ./env-setup.sh
install:
  - sudo -E su $USER -c "./pack-wrap.sh"
script:
  - sudo -E su $USER -c "PATH=/snap/bin:$PATH  packer build packer.json"
  - sudo -E su $USER -c "lxc image export ubuntu-xenial-timemachine"
  - ls -althr
