language: packer
sudo: required
dist: trusty
before_install:
  - sudo ./env-setup.sh
install:
  - sudo -E su $USER -c "./pack-wrap.sh"
script:
  - sudo -E su $USER -c "PATH=/snap/bin:$PATH  packer build packer.json"
